language: java

matrix:
  include:
    - os: linux
      sudo: required
      jdk: openjdk11
    - os: linux
      sudo: required
      jdk: openjdk12
      
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar      

script: ./gradlew check --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
